### ISSUE TITLE
Scripts page renders html as html

### ISSUE THREAD

**Issue by NigelThorne** [1999/controlfreak#18]
I had a script which was using JQuery to add a button to the screen. 

The scripts.html page doesn't realize the quoted html is part of the script and renders it as a button.

**Comment by 1999** [comment]
hm... could you provide a snippet which produces this behaviour?

**Comment by NigelThorne** [comment]
$(”<button id='test'>yay</button>").insertafter("#another");

This example would show a button in the preview.

**Comment by NigelThorne** [comment]
Lol... The github editor replaced my html.

**Comment by 1999** [comment]
https://yadi.sk/i/Gc5-EqV8mR6Wi
seems like everything okay?
